version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=MySqlDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password