version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=MySqlDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: