################################################
################# DEVELOPMENT ##################
################################################
name: test-YAML
environment: testing
enabled: false
servers:
  - www.abc.test.com
  - www.xyz.test.com
default-property-style:
  company-x:
    image-id: 486
    primary-color: #1e549d
  company-y:
    image-id: 486
    primary-color: #e30613
  company-z:
    image-id: 486
    primary-color: #02687f
  company-t:
    image-id: 486
    primary-color: #02687f