##############################
###### GENERAL SETTINGS ######
##############################
spring:
  application:
    name: SpringBoot 3 Development
  config:
    activate:
      on-profile: development
    import:
      - application-development.yml
###########################
#### DATABASE SETTINGS ####
###########################
  datasource:
    url: jdbc:mysql://localhost:3306/MySqlDB
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  ###########################
  ###### JPA SETTINGS #######
  ###########################
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
---
spring:
  application:
    name: SpringBoot 3 Production
  config:
    activate:
      on-profile: production
    import:
      - application-production.yml
