###########################
#### SECURITY SETTINGS ####
###########################
security:
  jwt:
    secret-key: wC0kL2XCJEbYITs2qJEBjA8NRFB3A54zh6EXMWvc6gCvY125VhR2aTf2FqxfJ1F26xWaPniR2mVh5nBpIlgDSdposd546SDgsdgSRDF35SDgjs4dsgsd542rtefSDGShfdh
    issuer: The Rebel Alliance
    expiration-in-ms: 14400000

##########################################
###### GENERAL SETTINGS DEVELOPMENT ######
##########################################
spring:
  application:
    name: SpringBoot 3 Development
  config:
    activate:
      on-profile: development
    import:
      - company-config-development.yml
  logging:
    level:
      org:
        springframework:
          context: DEBUG

  ###########################
  #### DATABASE SETTINGS ####
  ###########################
  datasource:
    url: jdbc:mysql://localhost:3306/MySqlDB
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  ###########################
  ###### JPA SETTINGS #######
  ###########################
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      format_sql: true
    database: mysql
    open-in-view: false
---
##########################################
###### GENERAL SETTINGS PRODUCTION ######
##########################################
spring:
  application:
    name: SpringBoot 3 Production
  config:
    activate:
      on-profile: production
    import:
      - company-config-production.yml

  ###########################
  #### DATABASE SETTINGS ####
  ###########################
  datasource:
    url: jdbc:mysql://localhost:3306/MySqlDB
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  ###########################
  ###### JPA SETTINGS #######
  ###########################
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false
    generate-ddl: true
    show-sql:  true
